################################################################################
# DATA CONFIG ##################################################################

dataset: ???

root: ???

tusz:
  version: "v2.0.3"

  user: ???python -m seiz_eeg.preprocess dataset=tusz tusz.user=$TUSZ_USER tusz.password=$TUSZ_PpW
  password: ???
  force_download: false

  raw: "${root}/TUSZ/${.version}"
  raw_edf: "${.raw}/edf"
  raw_doc: "${.raw}/_DOCS"

  processed: "${root}/TUSZ/processed"

  subsets:
    - dev
    - train
    - eval

  excluded_patients:
    dev:
      - "00001027"
      - "00001981"
      - "00004671"
      - "00006546"
      - "00009842"

labels:
  map:
    bckg: 0 # Background

    # SEIZURE LABEL - BINARY
    seiz: 1

    # COMBINED FOCAL
    spsz: 1 # Simple Partial Seizure
    cpsz: 1 # Complex Partial Seizure
    fnsz: 1 # Focal Non-Specific Seizure

    # COMBINED TONIC
    tnsz: 2 # Tonic Seizure
    cnsz: 2 # Clonic Seizure
    tcsz: 2 # Tonic Clonic Seizure

    # GENERALIZED NON-SPECIFIC
    gnsz: 3 # Generalized Non-Specific Seizure

    # Absence Seizure
    absz: 4 # Absence Seizure

    # EXCLUDED
    mysz: null # Myoclonic Seizure

  binary: false

signals:
  sampling_rate: 250 # Hz
